services:
  web:
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/1

    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations exchange &&
             python manage.py migrate &&
             python manage.py load_historical_dates &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test_currency_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_currency_exchange"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
